In [1]:
import nltk
import string
import pandas as pd 

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Abc\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Abc\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Abc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
text = """
Natural Language Processing (NLP) is amazing!
It helps computers understand human language,
and it is used in chatbots, search engines, and more.
"""

# this is our raw text

In [4]:
print("Original Text :")
print(text)

Original Text :

Natural Language Processing (NLP) is amazing!
It helps computers understand human language,
and it is used in chatbots, search engines, and more.

In [5]:
# tokenization starts from here

tokens = word_tokenize(text)
print("Tokens :")
print(tokens)

Tokens :
['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'amazing', '!', 'It', 'helps', 'computers', 'understand', 'human', 'language', ',', 'and', 'it', 'is', 'used', 'in', 'chatbots', ',', 'search', 'engines', ',', 'and', 'more', '.']

In [6]:
# converting is case-sensitive ... therefore converting it all to lowercase.

lower_tokens = [word.lower() for word in tokens]
print("Lower Tokens :")
print(lower_tokens)

Lower Tokens :
['natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'amazing', '!', 'it', 'helps', 'computers', 'understand', 'human', 'language', ',', 'and', 'it', 'is', 'used', 'in', 'chatbots', ',', 'search', 'engines', ',', 'and', 'more', '.']

In [7]:
# removing punctuations

tokens_without_punctuation = [
    word
    for word in lower_tokens
    if word not in string.punctuation
]

print("After removing punctuations : ")
print(tokens_without_punctuation)

After removing punctuations :
['natural', 'language', 'processing', 'nlp', 'is', 'amazing', 'it', 'helps', 'computers', 'understand', 'human', 'language', 'and', 'it', 'is', 'used', 'in', 'chatbots', 'search', 'engines', 'and', 'more']

In [ ]:
# stop words

stop_words = set(stopwords.words("english"))
print(stop_words)

{'didn', 'i', "she'll", 'above', 'were', 'all', 'while', 'ma', "they'll", 'where', 've', 'during', "haven't", "isn't", 'themselves', 'herself', 'should', 'most', "he's", 'd', 'y', 'only', 'out', 'been', "she's", 'if', "it's", 'between', 'but', "he'll", 'having', 'than', 'further', 'him', 'yours', "hadn't", 'off', "we've", 'to', 'own', 't', "it'd", 'this', 'once', "aren't", 'shan', 'other', 'so', 'who', "needn't", 'under', 'does', 'a', "you're", 'its', "i'm", 'until', "he'd", 'up', "wouldn't", 'she', 'be', 'wouldn', "should've", 'over', 'against', 'here', "you'd", 'down', 'just', 'm', 'our', 're', 'mightn', 'how', 'not', "mustn't", "i'd", "hasn't", 'at', 'you', 'he', 'me', 'has', 'that', 'then', 'about', "mightn't", 'it', 'his', 'is', 'doing', 'wasn', 'needn', 'o', 'yourselves', "don't", 'these', 'when', 'each', 's', 'through', 'we', "you'll", 'on', "we're", 'into', 'her', 'more', "they're", "won't", 'did', "it'll", 'they', 'ours', 'will', 'hers', 'll', 'with', 'again', 'there', 'mustn', 'had', 'yourself', 'haven', "couldn't", 'isn', 'whom', 'ain', 'won', 'my', 'before', 'couldn', 'being', 'hasn', 'as', 'was', 'weren', 'your', 'or', "weren't", "they've", 'myself', 'am', 'the', 'shouldn', 'very', "we'll", 'after', 'few', 'both', "we'd", "you've", 'which', 'an', 'himself', "i'll", 'no', "doesn't", "i've", 'in', "they'd", 'below', 'such', "didn't", 'of', 'doesn', 'don', "shan't", 'have', 'them', "she'd", 'now', "shouldn't", 'nor', "that'll", 'their', 'theirs', 'can', 'from', 'those', 'because', 'ourselves', 'itself', 'why', 'same', 'what', 'for', 'too', "wasn't", 'hadn', 'are', 'do', 'aren', 'by', 'any', 'and', 'some'}

In [9]:
# removing dtopwords from code

clean_tokens = [
    word
    for word in tokens_without_punctuation 
    if word not in stop_words
]
print("After removing stop words :")
print(clean_tokens)

After removing stop words :
['natural', 'language', 'processing', 'nlp', 'amazing', 'helps', 'computers', 'understand', 'human', 'language', 'used', 'chatbots', 'search', 'engines']

In [10]:
clean_text = " ".join(clean_tokens)

print("PreProcessed Text :")
print(clean_text)

PreProcessed Text :
natural language processing nlp amazing helps computers understand human language used chatbots search engines

In [11]:
# converting text into BaW

vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform([clean_text])

In [12]:
feature_names = vectorizer.get_feature_names_out()

print("Vocabulary:")
print(feature_names)

Vocabulary:
['amazing' 'chatbots' 'computers' 'engines' 'helps' 'human' 'language'
 'natural' 'nlp' 'processing' 'search' 'understand' 'used']

In [13]:
print("Bag of Words:")
print(bow_matrix.toarray())

Bag of Words:
[[1 1 1 1 1 1 2 1 1 1 1 1 1]]

In [14]:
bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=feature_names
)

bow_df

,amazing,chatbots,computers,engines,helps,human,language,natural,nlp,processing,search,understand,used
0,1,1,1,1,1,1,2,1,1,1,1,1,1

In [16]:
print("=" * 60)
print("1. ORIGINAL TEXT")
print("=" * 60)
print(text)

print("\n" + "=" * 60)
print("2. AFTER TOKENIZATION")
print("=" * 60)
print(tokens)

print("\n" + "=" * 60)
print("3. AFTER LOWERCASE CONVERSION")
print("=" * 60)
print(lower_tokens)

print("\n" + "=" * 60)
print("4. AFTER REMOVING PUNCTUATION")
print("=" * 60)
print(tokens_without_punctuation)

print("\n" + "=" * 60)
print("5. AFTER REMOVING STOP WORDS")
print("=" * 60)
print(clean_tokens)

print("\n" + "=" * 60)
print("6. FINAL PREPROCESSED TEXT")
print("=" * 60)
print(clean_text)

print("\n" + "=" * 60)
print("7. BAG OF WORDS")
print("=" * 60)
print(bow_df)

============================================================
1. ORIGINAL TEXT
============================================================

Natural Language Processing (NLP) is amazing!
It helps computers understand human language,
and it is used in chatbots, search engines, and more.


============================================================
2. AFTER TOKENIZATION
============================================================
['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'amazing', '!', 'It', 'helps', 'computers', 'understand', 'human', 'language', ',', 'and', 'it', 'is', 'used', 'in', 'chatbots', ',', 'search', 'engines', ',', 'and', 'more', '.']

============================================================
3. AFTER LOWERCASE CONVERSION
============================================================
['natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'amazing', '!', 'it', 'helps', 'computers', 'understand', 'human', 'language', ',', 'and', 'it', 'is', 'used', 'in', 'chatbots', ',', 'search', 'engines', ',', 'and', 'more', '.']

============================================================
4. AFTER REMOVING PUNCTUATION
============================================================
['natural', 'language', 'processing', 'nlp', 'is', 'amazing', 'it', 'helps', 'computers', 'understand', 'human', 'language', 'and', 'it', 'is', 'used', 'in', 'chatbots', 'search', 'engines', 'and', 'more']

============================================================
5. AFTER REMOVING STOP WORDS
============================================================
['natural', 'language', 'processing', 'nlp', 'amazing', 'helps', 'computers', 'understand', 'human', 'language', 'used', 'chatbots', 'search', 'engines']

============================================================
6. FINAL PREPROCESSED TEXT
============================================================
natural language processing nlp amazing helps computers understand human language used chatbots search engines

============================================================
7. BAG OF WORDS
============================================================
   amazing  chatbots  computers  engines  helps  human  language  natural  \
0        1         1          1        1      1      1         2        1

   nlp  processing  search  understand  used
0    1           1       1           1     1

In [17]:
# creting a reusable preprocessing functions 

def preprocess_text(text):

    # Tokenization
    tokens = word_tokenize(text)

    # Lowercase
    tokens = [
        word.lower()
        for word in tokens
    ]

    # Remove punctuation
    tokens = [
        word
        for word in tokens
        if word not in string.punctuation
    ]

    # Remove stop words
    stop_words = set(stopwords.words("english"))

    tokens = [
        word
        for word in tokens
        if word not in stop_words
    ]

    # Return cleaned text
    return " ".join(tokens)

In [21]:
cleaned_dataset = [
    preprocess_text(text)
    for text in clean_tokens
]

print(cleaned_dataset)

['natural', 'language', 'processing', 'nlp', 'amazing', 'helps', 'computers', 'understand', 'human', 'language', 'used', 'chatbots', 'search', 'engines']

In [22]:
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(cleaned_dataset)

bow_dataset = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

bow_dataset

,amazing,chatbots,computers,engines,helps,human,language,natural,nlp,processing,search,understand,used
0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,1,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0,0,0,0
6,0,0,1,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,1,0
8,0,0,0,0,0,1,0,0,0,0,0,0,0
9,0,0,0,0,0,0,1,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,0,0,1
11,0,1,0,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,1,0,0
13,0,0,0,1,0,0,0,0,0,0,0,0,0

In [23]:
print(X.toarray())

[[0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]]